config/routes.rb
Rails.application.routes.draw do
  resources :product_tables

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product_table.rb
class ProductTable < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/product_tables_controller.rb
class ProductTablesController < ApplicationController
  before_action :set_product_table, only: [:show, :edit, :update, :destroy]

  # GET /product_tables
  # GET /product_tables.json
  def index
    @product_tables = ProductTable.all
  end

  # GET /product_tables/1
  # GET /product_tables/1.json
  def show
  end

  # GET /product_tables/new
  def new
    @product_table = ProductTable.new
  end

  # GET /product_tables/1/edit
  def edit
  end

  # POST /product_tables
  # POST /product_tables.json
  def create
    @product_table = ProductTable.new(product_table_params)

    respond_to do |format|
      if @product_table.save
        format.html { redirect_to @product_table, notice: 'Product table was successfully created.' }
        format.json { render :show, status: :created, location: @product_table }
      else
        format.html { render :new }
        format.json { render json: @product_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_tables/1
  # PATCH/PUT /product_tables/1.json
  def update
    respond_to do |format|
      if @product_table.update(product_table_params)
        format.html { redirect_to @product_table, notice: 'Product table was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_table }
      else
        format.html { render :edit }
        format.json { render json: @product_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_tables/1
  # DELETE /product_tables/1.json
  def destroy
    @product_table.destroy
    respond_to do |format|
      format.html { redirect_to product_tables_url, notice: 'Product table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_table
      @product_table = ProductTable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_table_params
      params.require(:product_table).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_tables_helper.rb
module ProductTablesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/product_tables/_form.html.erb
<%= form_with(model: product_table, local: true) do |form| %>
  <% if product_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_table.errors.count, "error") %> prohibited this product_table from being saved:</h2>

      <ul>
        <% product_table.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_tables/edit.html.erb
<h1>Editing Product Table</h1>

<%= render 'form', product_table: @product_table %>

<%= link_to 'Show', @product_table %> |
<%= link_to 'Back', product_tables_path %>

app/views/product_tables/index.html.erb
<% if notice %>
<aside id="notice"><%= notice %></aside>
<% end %>

<h1>Products</h1>

<table>
<tfoot>
<tr>
<td colspan="3">
<%= link_to 'New Product', new_product_table_path %>
</td>
</tr>
</tfoot>
<tbody>
<%  @product_tables.each do |product| %>
<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

<td class="image">
<%= image_tag(product.image_url, class: 'list_image') %>
</td>

<td class="description">
<h1><%= product.title %></h1>
<p>
<%= truncate(strip_tags(product.description),
length: 80) %>
</p>
</td>

<td class="actions">
<ul>
<li><%= link_to 'Show', product %></li>
<li><%= link_to 'Edit', edit_product_table_path(product) %></li>
<li>
<%= link_to 'Destroy',
product,
method: :delete,
data: { confirm: 'Are you sure?' } %>
</li>
</ul>
</td>
</tr>
<% end %>
</tbody>
</table>

app/views/product_tables/new.html.erb
<h1>New Product Table</h1>

<%= render 'form', product_table: @product_table %>

<%= link_to 'Back', product_tables_path %>

app/views/product_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product_table.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product_table.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product_table.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product_table.price %>
</p>

<%= link_to 'Edit', edit_product_table_path(@product_table) %> |
<%= link_to 'Back', product_tables_path %>